export interface Language {
  code: string;
  name: string;
}

interface SupportedLanguages {
  [key: string]: Language;
}

export const supportedLanguages: SupportedLanguages = {
  'af-ZA': { code: 'af-ZA', name: 'Afrikaans (South Africa)' },
  'sq-AL': { code: 'sq-AL', name: 'Albanian (Albania)' },
  'am-ET': { code: 'am-ET', name: 'Amharic (Ethiopia)' },
  'ar-DZ': { code: 'ar-DZ', name: 'Arabic (Algeria)' },
  'ar-BH': { code: 'ar-BH', name: 'Arabic (Bahrain)' },
  'ar-EG': { code: 'ar-EG', name: 'Arabic (Egypt)' },
  'ar-IQ': { code: 'ar-IQ', name: 'Arabic (Iraq)' },
  'ar-IL': { code: 'ar-IL', name: 'Arabic (Israel)' },
  'ar-JO': { code: 'ar-JO', name: 'Arabic (Jordan)' },
  'ar-KW': { code: 'ar-KW', name: 'Arabic (Kuwait)' },
  'ar-LB': { code: 'ar-LB', name: 'Arabic (Lebanon)' },
  'ar-MA': { code: 'ar-MA', name: 'Arabic (Morocco)' },
  'ar-OM': { code: 'ar-OM', name: 'Arabic (Oman)' },
  'ar-QA': { code: 'ar-QA', name: 'Arabic (Qatar)' },
  'ar-SA': { code: 'ar-SA', name: 'Arabic (Saudi Arabia)' },
  'ar-PS': { code: 'ar-PS', name: 'Arabic (State of Palestine)' },
  'ar-TN': { code: 'ar-TN', name: 'Arabic (Tunisia)' },
  'ar-AE': { code: 'ar-AE', name: 'Arabic (United Arab Emirates)' },
  'ar-YE': { code: 'ar-YE', name: 'Arabic (Yemen)' },
  'hy-AM': { code: 'hy-AM', name: 'Armenian (Armenia)' },
  'az-AZ': { code: 'az-AZ', name: 'Azerbaijani (Azerbaijan)' },
  'eu-ES': { code: 'eu-ES', name: 'Basque (Spain)' },
  'bn-BD': { code: 'bn-BD', name: 'Bengali (Bangladesh)' },
  'bn-IN': { code: 'bn-IN', name: 'Bengali (India)' },
  'bs-BA': { code: 'bs-BA', name: 'Bosnian (Bosnia and Herzegovina)' },
  'bg-BG': { code: 'bg-BG', name: 'Bulgarian (Bulgaria)' },
  'my-MM': { code: 'my-MM', name: 'Burmese (Myanmar)' },
  'ca-ES': { code: 'ca-ES', name: 'Catalan (Spain)' },
  'yue-Hant-HK': { code: 'yue-Hant-HK', name: 'Chinese, Cantonese (Traditional Hong Kong)' },
  'zh (cmn-Hans-CN)': { code: 'zh (cmn-Hans-CN)', name: 'Chinese, Mandarin (Simplified, China)' },
  'zh-TW (cmn-Hant-TW)': {
    code: 'zh-TW (cmn-Hant-TW)',
    name: 'Chinese, Mandarin (Traditional, Taiwan)',
  },
  'hr-HR': { code: 'hr-HR', name: 'Croatian (Croatia)' },
  'cs-CZ': { code: 'cs-CZ', name: 'Czech (Czech Republic)' },
  'da-DK': { code: 'da-DK', name: 'Danish (Denmark)' },
  'nl-BE': { code: 'nl-BE', name: 'Dutch (Belgium)' },
  'nl-NL': { code: 'nl-NL', name: 'Dutch (Netherlands)' },
  'en-AU': { code: 'en-AU', name: 'English (Australia)' },
  'en-CA': { code: 'en-CA', name: 'English (Canada)' },
  'en-GH': { code: 'en-GH', name: 'English (Ghana)' },
  'en-HK': { code: 'en-HK', name: 'English (Hong Kong)' },
  'en-IN': { code: 'en-IN', name: 'English (India)' },
  'en-IE': { code: 'en-IE', name: 'English (Ireland)' },
  'en-KE': { code: 'en-KE', name: 'English (Kenya)' },
  'en-NZ': { code: 'en-NZ', name: 'English (New Zealand)' },
  'en-NG': { code: 'en-NG', name: 'English (Nigeria)' },
  'en-PK': { code: 'en-PK', name: 'English (Pakistan)' },
  'en-PH': { code: 'en-PH', name: 'English (Philippines)' },
  'en-SG': { code: 'en-SG', name: 'English (Singapore)' },
  'en-ZA': { code: 'en-ZA', name: 'English (South Africa)' },
  'en-TZ': { code: 'en-TZ', name: 'English (Tanzania)' },
  'en-GB': { code: 'en-GB', name: 'English (United Kingdom)' },
  'en-US': { code: 'en-US', name: 'English (United States)' },
  'et-EE': { code: 'et-EE', name: 'Estonian (Estonia)' },
  'fil-PH': { code: 'fil-PH', name: 'Filipino (Philippines)' },
  'fi-FI': { code: 'fi-FI', name: 'Finnish (Finland)' },
  'fr-BE': { code: 'fr-BE', name: 'French (Belgium)' },
  'fr-CA': { code: 'fr-CA', name: 'French (Canada)' },
  'fr-FR': { code: 'fr-FR', name: 'French (France)' },
  'fr-CH': { code: 'fr-CH', name: 'French (Switzerland)' },
  'gl-ES': { code: 'gl-ES', name: 'Galician (Spain)' },
  'ka-GE': { code: 'ka-GE', name: 'Georgian (Georgia)' },
  'de-AT': { code: 'de-AT', name: 'German (Austria)' },
  'de-DE': { code: 'de-DE', name: 'German (Germany)' },
  'de-CH': { code: 'de-CH', name: 'German (Switzerland)' },
  'el-GR': { code: 'el-GR', name: 'Greek (Greece)' },
  'gu-IN': { code: 'gu-IN', name: 'Gujarati (India)' },
  'iw-IL': { code: 'iw-IL', name: 'Hebrew (Israel)' },
  'hi-IN': { code: 'hi-IN', name: 'Hindi (India)' },
  'hu-HU': { code: 'hu-HU', name: 'Hungarian (Hungary)' },
  'is-IS': { code: 'is-IS', name: 'Icelandic (Iceland)' },
  'id-ID': { code: 'id-ID', name: 'Indonesian (Indonesia)' },
  'it-IT': { code: 'it-IT', name: 'Italian (Italy)' },
  'it-CH': { code: 'it-CH', name: 'Italian (Switzerland)' },
  'ja-JP': { code: 'ja-JP', name: 'Japanese (Japan)' },
  'jv-ID': { code: 'jv-ID', name: 'Javanese (Indonesia)' },
  'kn-IN': { code: 'kn-IN', name: 'Kannada (India)' },
  'kk-KZ': { code: 'kk-KZ', name: 'Kazakh (Kazakhstan)' },
  'km-KH': { code: 'km-KH', name: 'Khmer (Cambodia)' },
  'ko-KR': { code: 'ko-KR', name: 'Korean (South Korea)' },
  'lo-LA': { code: 'lo-LA', name: 'Lao (Laos)' },
  'lv-LV': { code: 'lv-LV', name: 'Latvian (Latvia)' },
  'lt-LT': { code: 'lt-LT', name: 'Lithuanian (Lithuania)' },
  'mk-MK': { code: 'mk-MK', name: 'Macedonian (North Macedonia)' },
  'ms-MY': { code: 'ms-MY', name: 'Malay (Malaysia)' },
  'ml-IN': { code: 'ml-IN', name: 'Malayalam (India)' },
  'mr-IN': { code: 'mr-IN', name: 'Marathi (India)' },
  'mn-MN': { code: 'mn-MN', name: 'Mongolian (Mongolia)' },
  'ne-NP': { code: 'ne-NP', name: 'Nepali (Nepal)' },
  'no-NO': { code: 'no-NO', name: 'Norwegian Bokmål (Norway)' },
  'fa-IR': { code: 'fa-IR', name: 'Persian (Iran)' },
  'pl-PL': { code: 'pl-PL', name: 'Polish (Poland)' },
  'pt-BR': { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  'pt-PT': { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  'pa-Guru-IN': { code: 'pa-Guru-IN', name: 'Punjabi (Gurmukhi India)' },
  'ro-RO': { code: 'ro-RO', name: 'Romanian (Romania)' },
  'ru-RU': { code: 'ru-RU', name: 'Russian (Russia)' },
  'sr-RS': { code: 'sr-RS', name: 'Serbian (Serbia)' },
  'si-LK': { code: 'si-LK', name: 'Sinhala (Sri Lanka)' },
  'sk-SK': { code: 'sk-SK', name: 'Slovak (Slovakia)' },
  'sl-SI': { code: 'sl-SI', name: 'Slovenian (Slovenia)' },
  'es-AR': { code: 'es-AR', name: 'Spanish (Argentina)' },
  'es-BO': { code: 'es-BO', name: 'Spanish (Bolivia)' },
  'es-CL': { code: 'es-CL', name: 'Spanish (Chile)' },
  'es-CO': { code: 'es-CO', name: 'Spanish (Colombia)' },
  'es-CR': { code: 'es-CR', name: 'Spanish (Costa Rica)' },
  'es-DO': { code: 'es-DO', name: 'Spanish (Dominican Republic)' },
  'es-EC': { code: 'es-EC', name: 'Spanish (Ecuador)' },
  'es-SV': { code: 'es-SV', name: 'Spanish (El Salvador)' },
  'es-GT': { code: 'es-GT', name: 'Spanish (Guatemala)' },
  'es-HN': { code: 'es-HN', name: 'Spanish (Honduras)' },
  'es-MX': { code: 'es-MX', name: 'Spanish (Mexico)' },
  'es-NI': { code: 'es-NI', name: 'Spanish (Nicaragua)' },
  'es-PA': { code: 'es-PA', name: 'Spanish (Panama)' },
  'es-PY': { code: 'es-PY', name: 'Spanish (Paraguay)' },
  'es-PE': { code: 'es-PE', name: 'Spanish (Peru)' },
  'es-PR': { code: 'es-PR', name: 'Spanish (Puerto Rico)' },
  'es-ES': { code: 'es-ES', name: 'Spanish (Spain)' },
  'es-US': { code: 'es-US', name: 'Spanish (United States)' },
  'es-UY': { code: 'es-UY', name: 'Spanish (Uruguay)' },
  'es-VE': { code: 'es-VE', name: 'Spanish (Venezuela)' },
  'su-ID': { code: 'su-ID', name: 'Sundanese (Indonesia)' },
  'sw-KE': { code: 'sw-KE', name: 'Swahili (Kenya)' },
  'sw-TZ': { code: 'sw-TZ', name: 'Swahili (Tanzania)' },
  'sv-SE': { code: 'sv-SE', name: 'Swedish (Sweden)' },
  'ta-IN': { code: 'ta-IN', name: 'Tamil (India)' },
  'ta-MY': { code: 'ta-MY', name: 'Tamil (Malaysia)' },
  'ta-SG': { code: 'ta-SG', name: 'Tamil (Singapore)' },
  'ta-LK': { code: 'ta-LK', name: 'Tamil (Sri Lanka)' },
  'te-IN': { code: 'te-IN', name: 'Telugu (India)' },
  'th-TH': { code: 'th-TH', name: 'Thai (Thailand)' },
  'tr-TR': { code: 'tr-TR', name: 'Turkish (Turkey)' },
  'uk-UA': { code: 'uk-UA', name: 'Ukrainian (Ukraine)' },
  'ur-IN': { code: 'ur-IN', name: 'Urdu (India)' },
  'ur-PK': { code: 'ur-PK', name: 'Urdu (Pakistan)' },
  'uz-UZ': { code: 'uz-UZ', name: 'Uzbek (Uzbekistan)' },
  'vi-VN': { code: 'vi-VN', name: 'Vietnamese (Vietnam)' },
  'zu-ZA': { code: 'zu-ZA', name: 'Zulu (South Africa)' },
};
